### ISSUE TITLE
Support for get_mut

### ISSUE THREAD

**Issue by Technohacker** [enlightware/typemap-meta#2]
Hello!
I was about to build my own compile-time type map when I stumbled across yours, thanks for this!

I was wondering if mutable access could be added. If required, I could make a PR for the same :)

**Comment by stephanemagnenat** [comment]
I guess mutable access could be added indeed. Feel free to make a PR, also add the corresponding tests please. Thank you!

**Comment by Technohacker** [comment]
Should I add them as separate test cases or is adding a few lines to test mutations to the existing ones enough?

**Comment by stephanemagnenat** [comment]
I would have specific tests for the equivalent of `impl_get` and `impl_get_ref`, but for the rest you might add to existing ones if it doesn't clutter them too much. However, when traits are involved (`derive_box_trait` and `derive_static_trait`), you'll likely need to create specific traits for the mut version, so it might be more readable to have them separate I would say.

**Comment by stephanemagnenat** [comment]
I've pushed version 0.2 with your additions. Thank you for your contributions!
